### ISSUE TITLE
SetLogVerbosityLevel and question about Hub and Dialer

### ISSUE THREAD

**Issue by Crispried** [egramtel/tdsharp#21]
Hello,

I got 2 questions:

1. How to change LogVerbosityLevel? I would like to avoid all this output
![image](https://user-images.githubusercontent.com/14315420/65833199-1255c380-e2d6-11e9-99b9-304ff8492cba.png)
In original tdlib it was possible to do in this way `Client.Execute(new TdApi.SetLogVerbosityLevel(0));`

I can find SetLogVerbosityLevel  in sources inside tdsharp repository but, I don't have it in TdLib which I uploaded from nuget.

2. Why I can't find Hub, Dialer and several other classes in sources but, they exist in TdLib which I got from nuget? Actually the reason why I'm trying to find sources is that I want to understand how Hub is implemented. Is that wrapper over ClientResultHandler in original tdlib? Could we have several hubs - for instance one for auth and another for handling other requests?

Thanks!

**Comment by x2bool** [comment]
Hi! You can't find Hub because in the newer version of this lib it has been removed. If you want to see the sources for 1.3 go to the 4f62c93cabc3a4b9c62cc7933c4190ef99b9a0e2 commit.

In 1.3 logging can be configured with a static method: Client.Log.SetVerbosityLevel(int level)

Having multiple hubs is probably a bad idea, unless you want a race between them for messages from tdlib. I would create a single Hub and then route messages to different handlers depending on their type.

P.S. Creating the Hub class probably was a bad design decision, use the latest version if you can. 1.4 can be found on the master branch of this repo. NuGet packages will be available after I fix Client disposal.

**Comment by Crispried** [comment]
@x2bool 
Thanks for the explanations I think there is no reasons to not use the latest version.
