### ISSUE TITLE
Failed to parse JSON object as TDLib request: Unknown class "updateOption"

### ISSUE THREAD

**Issue by Marjani** [egramtel/tdsharp#37]
Hi
I download current source and add tdlib.native package from nuget to TDLib.Samples.GetChats project, update ApId and ApiHash and PhoneNumber, then run. after few moments exception occurred.

`TdLib.TdException: 'Failed to parse JSON object as TDLib request: Unknown class "updateOption"'
`
latest line of output:

```
'TDLib.Samples.GetChats.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Exception thrown: 'TdLib.TdException' in System.Private.CoreLib.dll
An exception of type 'TdLib.TdException' occurred in System.Private.CoreLib.dll but was not handled in user code
Failed to parse JSON object as TDLib request: Unknown class "updateOption
```
image : https://ibb.co/6RY8bs0

**Comment by x2bool** [comment]
@dariooo512 what was the purpose of SetOption function call here: https://github.com/egramtel/tdsharp/blob/master/Samples/TdLib.Samples.GetChats/Program.cs#L28 ?

**Comment by Inetov** [comment]
I have same problem. This code [master/Samples/TdLib.Samples.GetChats](https://github.com/egramtel/tdsharp/tree/master/Samples/TdLib.Samples.GetChats) doesn't work!

@x2bool, I did not understand your question...

**Comment by dariooo512** [comment]
> @dariooo512 what was the purpose of SetOption function call here: https://github.com/egramtel/tdsharp/blob/master/Samples/TdLib.Samples.GetChats/Program.cs#L28 ?

Hi, that code is used to set options coming from the server such as max message length.

**Comment by dariooo512** [comment]
> I have same problem. This code [master/Samples/TdLib.Samples.GetChats](https://github.com/egramtel/tdsharp/tree/master/Samples/TdLib.Samples.GetChats) doesn't work!
> 
> @x2bool, I did not understand your question...

Did you set the param with your Telegram app data? (ApiId, ApiHash, PhoneNumber)

**Comment by Inetov** [comment]
> Did you set the param with your Telegram app data? (ApiId, ApiHash, PhoneNumber)

sure
![изображение](https://user-images.githubusercontent.com/45286374/76798077-f096bd00-67df-11ea-94f8-ec10038589a9.png)

**Comment by dariooo512** [comment]
Looks like the version upgrade from 1.4.0 to 1.6.0 did break that request. (Looks like a mismatch between request Json schema and related class model)

**Comment by ageiter** [comment]
Hi, 
I have the same problem. Is there already a solution or workaround to this issue? 
I have commented out the code in the case UpdateOption and then the query GetChats works. But the options are not saved then.

**Comment by x2bool** [comment]
@ageiter  The workaround for now is to comment out SetOption call

**Comment by x2bool** [comment]
`updateOption` is clearly defined: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L3005

And it seems there is no mismatch between the types. tdlib for some reason doesn't recognize `updateOption` class. hmm... What actual subtype of the OptionValue are you getting?

**Comment by StruninIhor** [comment]
> `updateOption` is clearly defined: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L3005
> 
> And it seems there is no mismatch between the types. tdlib for some reason doesn't recognize `updateOption` class. hmm... What actual subtype of the OptionValue are you getting?
Hi I'm facing the same issue. 
Hope that will help
![image](https://user-images.githubusercontent.com/25036423/80909657-ac7d5e80-8d32-11ea-9168-e713c4950d6d.png)

**Comment by bretbas** [comment]
I have the same problem...

**Comment by Ilya93** [comment]
Me too..

**Comment by matheusrochabume** [comment]
I have the same problem, has anyone managed to solve it?

**Comment by Xilosof** [comment]
Hi. I have the same problem. I am compile 1.7 tdlib and generate new classes with your code generator, but the problem was not solved. Another functions works correctly. 
![изображение](https://user-images.githubusercontent.com/49105199/104119612-85efd880-5341-11eb-8026-2fee51f3e5f6.png)
This happens when I try to run your sample project. If I comment "setOption", everything works fine

**Comment by Xilosof** [comment]
Ok, after several hours of searching, I understand that we do not need to install the options that come by update. I got a few new errors before I realized it. Here's the timeline:

1) Failed to parse JSON object as TDLib request: Unknown class "updateoption" - this error occurred due to overriding the datatype parameter. It is not necessary to touch it, it is a kind of class name for the json format. The Extra parameter can also be left untouched, because it is used by the library, for example, for id. You can simply delete these parameters and use the setOption method according to the documentation https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_option.html, passing only two parameters.
After that, I started getting another error. 
2) TDLib. tdexception: "Option can't be set" - Starting immediately with the "version" option. https://core.telegram.org/tdlib/options. According to the same documentation, the options on which such an exception was made are forbidden to write. It is logical, because we do not need to change the version of tdlib. Therefore, updateoption only informs our application about the option change or occurs during initialization. For example so that we can correctly display the current version in the corner of the app)))

I checked the documentation and it is not written anywhere in the need to set options after getting the event. And in the examples, it is often ignored in general.
Solution: do not set the options that came for the event updateoption
