### ISSUE TITLE
Is it possible to update the library to the latest version?

### ISSUE THREAD

**Issue by AppcenterAucxis** [egramtel/tdsharp#71]
Is it possible to update the library to the latest version?
Or can I find any instructions to update the library?

I want to use the extended version of the generateChatInviteLink

**Comment by sanderwollaert** [comment]
+1

**Comment by x2bool** [comment]
Sure it is possible. However TDLib (Telegram) developers have very unclear release policy. They don't tag intermediate releases, and just add (sometimes breaking) changes into the master branch of TDLib. It is impossible to target particular version, and new minor releases often break someones code.

**Comment by wiz0u** [comment]
Could you tag your nuget package 1.7 as prerelease, so that we don't take it until tdlib.native is finally available in version 1.7 ?

I spent a week trying to understand why this lib wasn't working properly, finally understanding that your lib 1.7 is incompatible with tdlib.native 1.6.
Using your lib in version 1.6 makes things work better.

**Comment by x2bool** [comment]
I understand your concerns. But tdlib.native is an independent project maintained by someone other than me. What if the native nuget never gets updated? Should TDSharp stay forever in prerelease in that case? Another thing that I mentioned above: 1.7 constantly gets updates, and there is no guarantee that 1.7 will stay compatible with what they have in the repo right now.

**Comment by x2bool** [comment]
1.7.9 is now on NuGet
