### ISSUE TITLE
Logging cannot be silenced.

### ISSUE THREAD

**Issue by emctague** [egramtel/tdsharp#88]
I am trying to use TDSharp to make a TUI application, so I need to totally silence log output. However, in spite of beginning my program like so:

```cs
            client = new TdClient();
            await client.SetLogStreamAsync(new TdApi.LogStream.LogStreamEmpty());
            client.Bindings.SetLogVerbosityLevel(0);
```

I still get a few lines of output on the console at program start, such as:

```
Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.7.0"
  }
}
```

Why does a verbosity level of 0 not silence logging? Is there some other route to make the library stop printing?

**Comment by ForNeVeR** [comment]
I was able to reproduce this. The problem is that `new TdClient()` calls `new TdJsonClient()` which, in turn, calls `ITdLibBinginds::ClientCreate()`, which prints stuff to the log.

I was able to work around that by making `TdLib.Bindings.Interop` and `TdLib.Bindings.Interop.AutoDetectBindings` public and then using the following code:
```csharp
            var bindings = Interop.AutoDetectBindings();
            bindings.SetLogVerbosityLevel(0);

            _client = new TdClient(bindings);
```

Not sure what the right solution would be. I'm open for suggestions.

**Comment by ForNeVeR** [comment]
After thinking about it a while, I think that the solution above is the right one. Making `TdJsonClient` to call `ClientCreate` in a lazy way is tricky and not worth it. Let's just make the stuff public, so people may augment the default autodetected `Bindings` in the way they want.

See https://github.com/egramtel/tdsharp/pull/89.
