### ISSUE TITLE
UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by l8984** [egramtel/tdsharp#94]
Login prompt Error UPDATE_APP_TO_LOGIN

**Comment by ForNeVeR** [comment]
Sorry, it is unclear what you are asking. Could you please elaborate?

**Comment by l8984** [comment]
Can I speak Chinese？
前几天程序调用 tdsharp 正常，今天突然登录的时候报错了，Telegram 提示错误：UPDATE_APP_TO_LOGIN。这个错误是不是因为要升级 TDLib 的版本过低，需要升级自后才能使用？
调用代码：

mTdClient.SetAuthenticationPhoneNumberAsync(AppConfig.LoginConfig.PhoneNumber).ContinueWith(delegate (Task<TdApi.Ok> result)
{
    if (result.Exception != null)
    {
        //这里异常 UPDATE_APP_TO_LOGIN			
    }
});

**Comment by Arturiby** [comment]
@ForNeVeR 
The Telegram team disabled login functionality for all libraries what use outdated tdlib versions.

Currently it is not possible to invoke `TdApi.SetAuthenticationPhoneNumber` request without updating to tdlib 1.7.9. https://github.com/tdlib/td/issues/1758.

Any chance to get it works soon? Update TDLib.Native nuget package, etc. ?

**Comment by ForNeVeR** [comment]
Oh gosh. Thanks for the information, I'll take a look.

**Comment by x2bool** [comment]
Yeah. Can confirm. Telegram notified about this today.

> make sure your app supports this API layer: https://core.telegram.org/api/layers#layer-133

> int64 IDs. Your app will need to support these new IDs as soon as possible

> Mandatory support for sponsored messages.

I think the whole thing is about this

**Comment by l8984** [comment]
@ForNeVeR @x2bool 
Will tdsharp here be updated

**Comment by ForNeVeR** [comment]
Yes, it will be.

**Comment by farhad-rad** [comment]
How long do you estimate that it would take to update this library based on telegram API layer 133 (As mentioned above)?
Main telegram TDLib is updated already; thought it might be helpful.

**Comment by alexandrsemenovsmr** [comment]
Could you please update nuget packages to version 1.7.9 of the libraries "TDLib", "TDLib.Api" and "tdlib.native"?

**Comment by x2bool** [comment]
Yeah! We understand this is urgent, because older version basically stopped working. I will generate bindings ASAP.

@ForNeVeR I guess we have to pick some specific commit for which we will generate new bindings?

**Comment by l8984** [comment]
@x2bool @ForNeVeR 
Thanks！

**Comment by x2bool** [comment]
I asked here: https://github.com/tdlib/td/issues/1758 what commit could be used for 1.7.9

**Comment by l8984** [comment]
@x2bool 
我构建了最新的 tdlib/td 可以登录了，不过 tdsharp 需要对应升级才行，不然JSON反序列化会报错！希望尽快更新！感谢！

**Comment by alexandrsemenovsmr** [comment]
@x2bool , is it possible to update nuget packages today?

**Comment by fernandonajera** [comment]
I've created a pull request if that helps.

**Comment by x2bool** [comment]
@fernandonajera Yes. PR definitely did help, thanks.

I've published TDLib.Api & TDLib of version 1.7.9 to nuget.org

Please don't forget that you can compile the native part of TDLib yourself as a temp solution before TDLib.Native will be published.

**Comment by fernandonajera** [comment]
Glad to be of help! I've never compiled TDLib myself, let's see how far I can get.

**Comment by x2bool** [comment]
Guys, please do not message me in Telegram, there are too many people trying to do this right now.

I don't do support in DMs, I won't read your message and won't answer to your question. Thank you for understanding.

**Comment by ForNeVeR** [comment]
@x2bool, please don't forget tp push a new release tag. Thanks!

**Comment by fernandonajera** [comment]
@x2bool @ForNeVeR I have a pull request for the tdlib.native library. I have just moved the subrepositories and let the action run. Unfortunately I didn't find the generated Windows/Linux libraries (the OSX it's there, funny enough).
I don't know what else I can do to help here.

**Comment by v1adislave** [comment]
@x2bool with the latest release of tdsharp (tdlib 1.7.9 updated bindings), I'm getting error DLLNotFound . I'm trying to use it with docker ( Debian 10 ), .net core 3.1. What did I missed?

**Comment by ForNeVeR** [comment]
[tdlib.native v1.7.9](https://www.nuget.org/packages/tdlib.native/1.7.9) has been published.

@x2bool, I believe we can close this issue, two points though:
1. It would be nice to keep the issue "pinned" in the repository for a week or so, since more people will definitely come looking for it.
   <img width="316" alt="image" src="https://user-images.githubusercontent.com/92793/144717692-14ff0b71-8d4f-42b9-b31c-e6d7c00d6d33.png">
2. It would be nice to receive a confirmation from someone that the new releases (of both tdlib.native and tdsharp v1.7.9) work well together (sure, we have some simple unit tests, but nothing is better than a real user's check).

**Comment by fernandonajera** [comment]
Confirmation, from an app using these libraries even though in a quite limited extend:

* Windows version seems to work - .NET Core 3.1 (no Docker).
* Deployment version seems to work too (Ubuntu 18)

I did get a NullReferenceException I didn't have before - I'll investigate, but I doubt it's related to these latest commits (more probably I have to adapt the code to the many changes happened since I last updated the libraries)

**Comment by fernandonajera** [comment]
@ForNeVeR  @x2bool some more debugging:

<pre>
     18426:     checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /sites/qsb/runtimes/linux-x64/native/libtdjson.so [0]
     18426:     checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libm.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native/libtdjson.s
     18426:     checking for version `OPENSSL_1_1_0' in file /usr/lib/x86_64-linux-gnu/libssl.so.1.1 [0] required by file /sites/qsb/runtimes/linux-x64/native/l
     18426:     checking for version `OPENSSL_1_1_1' in file /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 [0] required by file /sites/qsb/runtimes/linux-x64/nativ
     18426:     checking for version `OPENSSL_1_1_0' in file /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 [0] required by file /sites/qsb/runtimes/linux-x64/nativ
     18426:     checking for version `GLIBCXX_3.4.14' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native
     18426:     checking for version `GLIBCXX_3.4.19' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native
     18426:     checking for version `CXXABI_1.3' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native/lib
     18426:     checking for version `GLIBCXX_3.4.18' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native
     18426:     checking for version `GLIBCXX_3.4.9' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native/
     18426:     checking for version `CXXABI_1.3.5' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native/l
     18426:     checking for version `GLIBCXX_3.4.11' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native
     18426:     checking for version `GLIBCXX_3.4.26' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /sites/qsb/runtimes/linux-x64/native
     18426:     /usr/lib/x86_64-linux-gnu/libstdc++.so.6: error: version lookup error: version `GLIBCXX_3.4.26' not found (required by /sites/qsb/runtimes/linux
     18426:
     18426:     file=/sites/qsb/runtimes/linux-x64/native/libtdjson.so [0];  destroying link map
</pre>

**Comment by fernandonajera** [comment]
Quick workaround for Ubuntu 18 (maybe helps @v1adislave ?):

<pre>
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
</pre>

**Comment by v1adislave** [comment]
@fernandonajera Unfortunately, didn't help. 

My dockerfile:

`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
WORKDIR /app

RUN apt-get update
RUN apt-get install sudo
RUN sudo apt-get  -y install software-properties-common 
RUN sudo add-apt-repository ppa:ubuntu-toolchain-r/test
RUN sudo apt-get -y install gcc-9
RUN sudo apt-get -y install libstdc++6

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic AS build
WORKDIR /src
COPY ["XXX.Site.csproj", "XXX.Site.csproj"]
RUN dotnet restore "XXX.Site.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "XXX.Site.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "XXX.Site.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "XXX.Site.dll"]`

Error I get:

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'tdjson' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libtdjson: cannot open shared object file: No such file or directory
   at TdLib.Bindings.LinuxBindings.td_json_client_create()
   at TdLib.Bindings.LinuxBindings.ClientCreate()
   at TdLib.TdJsonClient..ctor(ITdLibBindings bindings)
   at TdLib.TdClient..ctor(ITdLibBindings bindings)
   at TdLib.TdClient..ctor()`

**Comment by Arturiby** [comment]
@v1adislave have you also copied tdlib binaries (libtdjson.so) to the root of your app?

**Comment by v1adislave** [comment]
@Arturiby I installed TDLib.native nuget package (1.7.9)

**Comment by ForNeVeR** [comment]
@v1adislave, thanks to help from @fernandonajera, I was able to figure out what's going on. Please follow https://github.com/ForNeVeR/tdlib.native/issues/51 (it is a tdlib.native issue, not tdsharp one), and ask any further questions there.

**Comment by farhad-rad** [comment]
calling ```TdApi.Client.CheckDatabaseEncryptionKeyAsync``` shuts the application down in any of debug and release levels; and leaves no exception and stack trace!

**Comment by Jeffy94** [comment]
@ForNeVeR @x2bool 
**Please** help me find a solution!
After installing TDLib, TDLib.Api, tdlib.native works correctly on Windows.
But after building the APK and running it on **Android**, it gives an error.
**DllNotFoundException: Unable to load DLL 'tdjson': The specified module could not be found.**
![image](https://user-images.githubusercontent.com/83750645/161518067-05369b58-9a7b-45e5-b0e2-2df06c8b902f.png)
**Links to used libraries:**
https://www.nuget.org/packages/TDLib/
https://www.nuget.org/packages/TDLib.Api/
https://www.nuget.org/packages/tdlib.native/
https://www.nuget.org/packages/Newtonsoft.Json/
**Link to instructions:**
https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/unity-scripting-upgrade#add-packages-from-nuget-to-a-unity-project
**Link.xml File:**
![image](https://user-images.githubusercontent.com/83750645/161518854-6c527c00-a5f3-4006-8353-e6cbcc7bdb1e.png)

**Comment by ForNeVeR** [comment]
@Jeffy94, please stop spamming unrelated issues. If you aren't getting an issue discussed in this thread, then don't write responses to this thread.

Also, I don't know anything about Android, sorry.
